#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
if [ -f .coffee ] && [ -x `which coffeetags` ]; then
  ctags='coffeetags'
  options='--tag-relative'
else
  ctags='ctags'
  options="--options=`stat -f '%N' ~/.ctags-options`"
fi
$ctags -Rf.git/tags.$$ $options
mv .git/tags.$$ .git/tags
