#!/bin/sh

set -e

if [ "$PWD" = "$HOME" ]; then
  exit 0
fi

PATH="/usr/local/bin:$PATH"

tagsfile=".git/tags.$$"

trap "rm -f $tagsfile" EXIT

exclude_options="--exclude=.git --exclude=@`stat -f '%N' .gitignore` --exclude=@`stat -f '%N' ~/.gitignore_global`"
if [ -f .ctags.ignore ]; then
  exclude_options="$exclude_options --exclude=@`stat -f '%N' .ctags.ignore`"
fi

common_options="--fields=fKlsSzt --sort=foldcase --tag-relative=yes $exclude_options"

ctags -Rf$tagsfile $common_options

if [ -f .ctags.local ]; then
  local_options="--options=`stat -f '%N' .ctags.local` $common_options"
  ctags -aRf$tagsfile $local_options
fi

mv $tagsfile .git/tags
