tap "1password/tap"
tap "candid82/brew" # joker for goku
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "saulpw/vd" # visidata
tap "sourcegraph/src-cli"
tap "yqrashawn/goku" # goku

brew "awscli"
brew "bat"
brew "btop"
brew "chrome-cli"
brew "csvlens"
brew "d12frosted/emacs-plus/emacs-plus@30", args: ["with-modern-doom3-icon"]
brew "datasette"
brew "direnv"
brew "entr"
brew "eza"
brew "fd"
brew "fdupes"
brew "ffmpeg"
brew "fx"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "gmailctl"
brew "gum"
brew "httperf"
brew "httpie"
brew "hyperfine"
brew "ispell"
brew "jless"
brew "jq"
brew "llm"
brew "lua"
brew "luarocks"
brew "marksman"
brew "mas"
brew "ncdu"
brew "node"
brew "pgcli"
brew "pipx"
brew "protobuf", link: false
brew "python@3.10"
brew "python@3.11"
brew "python@3.12"
brew "rbenv"
brew "ripgrep"
brew "ruby-build"
brew "ruby-lsp"
brew "rust"
brew "saulpw/vd/visidata"
brew "semgrep"
brew "shellcheck"
brew "shfmt"
brew "spark"
brew "terraformer"
brew "tesseract"
brew "tidy-html5"
brew "tmux"
brew "ugrep"
brew "uv"
brew "vhs"
brew "wget"
brew "yqrashawn/goku/goku"
brew "zsh"
brew "zstd"

cask "1password"
cask "1password-cli"
cask "bettertouchtool"
cask "dash"
cask "fantastical"
cask "firefox"
cask "font-iosevka"
cask "font-iosevka-aile"
cask "font-iosevka-etoile"
cask "font-iosevka-nerd-font"
cask "google-chrome"
cask "hammerspoon"
cask "hazeover"
cask "iterm2"
cask "karabiner-elements"
cask "notion"
cask "notion-calendar"
cask "slack"
cask "soulver"
cask "yubico-yubikey-manager"

if ENV['PERSONAL_BREW']
  tap "keith/formulae" #reminders-cli
  tap "pulumi/tap"
  tap "xenodium/macosrec" # macosrec

  brew "keith/formulae/reminders-cli"
  brew "pulumi/tap/pulumi"
  brew "xenodium/macosrec/macosrec"
  brew "yt-dlp"

  cask "qflipper"
  cask "sparrow"
  cask "steam"
  cask "vlc"
  cask "zoom"

  mas "Reeder", id: 1529448980
  mas "Wallpaper Wizard", id: 1266674560
  mas "Xcode", id: 497799835
end

Dir['.Brewfile.*'].each { |brewfile| load brewfile }
