tap 'homebrew/bundle'
brew 'ctags'
brew 'docker'
brew 'docker-machine'
brew 'duck'
brew 'git'
brew 'hub'
brew 'httpie'
brew 'jq'
brew 'macvim', args: ['HEAD', 'with-lua', 'with-luajit', 'with-override-system-vim', 'with-python3']
brew 'ncdu'
brew 'nodejs'
brew 'pgcli'

brew 'python3'

brew 'rbenv'
brew 'ruby-build'

brew 'the_silver_searcher'
brew 'tig', args: ['HEAD']
brew 'tree'
brew 'unrar'
brew 'wget'
brew 'zsh'

tap 'd12frosted/emacs-plus'
brew 'emacs-plus'

tap 'homebrew/completions'
brew 'homebrew/completions/vagrant-completion'

tap 'caskroom/cask'
#brew 'caskroom/cask/brew-cask'
cask 'alfred'
cask 'bartender'
cask 'bettertouchtool'
cask 'cyberduck'
cask 'dash'
cask 'dropbox'
cask 'flux'
cask 'java'
cask 'karabiner'
cask 'knock'
cask 'moom'
cask 'postgres'
cask 'rescuetime'
cask 'quip'
cask 'shortcat'
cask 'soundflower'
cask 'textexpander'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'vox'
cask 'vox-preferences-pane'
cask 'xscreensaver'

tap 'caskroom/fonts'
tap 'caskroom/homebrew-fonts'
cask 'font-glober'
cask 'font-source-code-pro-for-powerline'

tap 'caskroom/versions'
tap 'caskroom/homebrew-versions'
cask 'fantastical'
cask 'google-chrome-beta'
cask 'iterm2-beta'
