#! /bin/zsh -f

HASHSTRING=`hostname`

if [[ $DISTRO = "CentOS" ]]; then
        HASHSTRING="`hostname -f`"
fi

HOSTCOLORCODE=255
`qwhich hosts.rb > /dev/null` && HOSTCOLORCODE=$(hosts.rb -d $HASHSTRING)

[[ $TERM = 'eterm-color' ]] && HOSTCOLORCODE=34

ESCAPE=$'%{\e[%}'

HOSTCOLORESCAPE=$'%{'$ESCAPE'38;5;'$HOSTCOLORCODE$'m%}'

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' get-revision true

zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' stagedstr '-'
zstyle ':vcs_info:*' actionformats '%b%c%u|%a'
zstyle ':vcs_info:*' formats '%b [%c] %u'
zstyle ':vcs_info:*' branchformat '%b'

zstyle ':vcs_info:*' enable svn bzr hg git

colors
precmd

function hg_prompt() {
    local HG_PROMPT_FORMAT='{:{node|short}}{ {status|modified|unknown}}{update}{ >{incoming|count}}{ {outgoing|count}>}'
    export HG_PROMPT=""
    hg prompt &> /dev/null && export HG_PROMPT="`hg prompt $HG_PROMPT_FORMAT 2> /dev/null`"
}

function zsh_prompt()
{
        local N=$'%{'$ESCAPE'0m%}'    # unsets color to term's fg color

        local UC=$HOSTCOLORESCAPE # user's color

        local O="${UC}:${N}"
        local C="${UC}:${N}"

        local D="${UC}-${N}"

        [[ $UID -eq "0" ]] && O="${UC}[${N}"
        [[ $UID -eq "0" ]] && C="${UC}]${N}"
        [[ $UID -eq "0" ]] && D="${UC}-${N}"


        local HO=$HOSTCOLORESCAPE
        local HC=$N

        local PRETTY_WD=`rtab -f`

        export PROMPT="
${UC}${PRETTY_WD}${N}» "
        export RPROMPT="${UC}%n${N}@${UC}%m${N} | %(0?,,${UC}%?!${N} )${UC}${vcs_info_msg_0_}${HG_PROMPT}${N}"
        export PS2="${D}${O}"
}

if [[ "$TERM" = "dumb" ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='- '
else
  (( ${+functions[vcs_info]} )) && vcs_info
  zsh_prompt
fi
