#! /bin/zsh -f

function wgadmin {
  sudo -su wgadmin
}

function wf {
  cd /opt/workfeed/current
  export PATH="/opt/ruby-enterprise/bin:$PATH:$HOME/bin:/usr/sbin:/sbin"
  export RAILS_ENV=production
}

function rc { bundle exec rails c }
