#! /bin/zsh -f

zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "\e[A" history-beginning-search-backward-end
bindkey "\e[B" history-beginning-search-forward-end
bindkey "\eOA" history-beginning-search-backward-end
bindkey "\eOB" history-beginning-search-forward-end

zle -N history-beginning-search-menu-space-end history-beginning-search-menu
bindkey "\e\e[A" history-beginning-search-menu-space-end
bindkey "\e\eOA" history-beginning-search-menu-space-end

bindkey "\C-z" undo
bindkey " " magic-space

zle -N expand-or-complete-prefix-with-dots
bindkey '^I' expand-or-complete-prefix-with-dots

bindkey "^[[Z" reverse-menu-complete
bindkey "^[" send-break

bindkey "^[e" backward-kill-word
bindkey "^[w" backward-kill-word

bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

bindkey "^[[3~" delete-char-or-list

bindkey "^Q" push-input
bindkey "^[Q" push-input
bindkey "^[q" push-input