#! /bin/zsh -f

zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "\e[A" history-beginning-search-backward-end
bindkey "\e[B" history-beginning-search-forward-end
bindkey "\eOA" history-beginning-search-backward-end
bindkey "\eOB" history-beginning-search-forward-end

zle -N history-beginning-search-menu-space-end history-beginning-search-menu
bindkey "\e\e[A" history-beginning-search-menu-space-end
bindkey "\e\eOA" history-beginning-search-menu-space-end

bindkey "\C-z" undo
bindkey " " magic-space

bindkey '^i' expand-or-complete-prefix