# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cutehg/views/layouts/statuslayout.ui'
#
# Created: Wed Jun  3 10:23:39 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_StatusLayout(object):
    def setupUi(self, StatusLayout):
        StatusLayout.setObjectName("StatusLayout")
        StatusLayout.resize(451, 337)
        self.verticalLayout = QtGui.QVBoxLayout(StatusLayout)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterEdit = QtGui.QLineEdit(StatusLayout)
        self.filterEdit.setObjectName("filterEdit")
        self.verticalLayout.addWidget(self.filterEdit)
        self.widget = QtGui.QWidget(StatusLayout)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.modifiedCheckBox = QtGui.QCheckBox(self.widget)
        self.modifiedCheckBox.setObjectName("modifiedCheckBox")
        self.horizontalLayout.addWidget(self.modifiedCheckBox)
        self.addedCheckBox = QtGui.QCheckBox(self.widget)
        self.addedCheckBox.setObjectName("addedCheckBox")
        self.horizontalLayout.addWidget(self.addedCheckBox)
        self.removedCheckBox = QtGui.QCheckBox(self.widget)
        self.removedCheckBox.setObjectName("removedCheckBox")
        self.horizontalLayout.addWidget(self.removedCheckBox)
        self.deletedCheckBox = QtGui.QCheckBox(self.widget)
        self.deletedCheckBox.setObjectName("deletedCheckBox")
        self.horizontalLayout.addWidget(self.deletedCheckBox)
        self.unknownCheckBox = QtGui.QCheckBox(self.widget)
        self.unknownCheckBox.setObjectName("unknownCheckBox")
        self.horizontalLayout.addWidget(self.unknownCheckBox)
        self.ignoredCheckBox = QtGui.QCheckBox(self.widget)
        self.ignoredCheckBox.setObjectName("ignoredCheckBox")
        self.horizontalLayout.addWidget(self.ignoredCheckBox)
        self.cleanCheckBox = QtGui.QCheckBox(self.widget)
        self.cleanCheckBox.setObjectName("cleanCheckBox")
        self.horizontalLayout.addWidget(self.cleanCheckBox)
        self.verticalLayout.addWidget(self.widget)
        self.scrollArea = QtGui.QScrollArea(StatusLayout)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -126, 420, 461))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.parent1Container = QtGui.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parent1Container.sizePolicy().hasHeightForWidth())
        self.parent1Container.setSizePolicy(sizePolicy)
        self.parent1Container.setObjectName("parent1Container")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.parent1Container)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_5 = QtGui.QWidget(self.parent1Container)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.widget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.parent1Label = QtGui.QLabel(self.widget_5)
        self.parent1Label.setObjectName("parent1Label")
        self.horizontalLayout_3.addWidget(self.parent1Label)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.parent1TableView = QtGui.QTableView(self.parent1Container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parent1TableView.sizePolicy().hasHeightForWidth())
        self.parent1TableView.setSizePolicy(sizePolicy)
        self.parent1TableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parent1TableView.setAlternatingRowColors(False)
        self.parent1TableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.parent1TableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.parent1TableView.setShowGrid(False)
        self.parent1TableView.setSortingEnabled(True)
        self.parent1TableView.setObjectName("parent1TableView")
        self.verticalLayout_4.addWidget(self.parent1TableView)
        self.verticalLayout_2.addWidget(self.parent1Container)
        self.parent2Container = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.parent2Container.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parent2Container.sizePolicy().hasHeightForWidth())
        self.parent2Container.setSizePolicy(sizePolicy)
        self.parent2Container.setObjectName("parent2Container")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.parent2Container)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line = QtGui.QFrame(self.parent2Container)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.widget_2 = QtGui.QWidget(self.parent2Container)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.widget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.parent2Label = QtGui.QLabel(self.widget_2)
        self.parent2Label.setObjectName("parent2Label")
        self.horizontalLayout_2.addWidget(self.parent2Label)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.parent2TableView = QtGui.QTableView(self.parent2Container)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parent2TableView.sizePolicy().hasHeightForWidth())
        self.parent2TableView.setSizePolicy(sizePolicy)
        self.parent2TableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.parent2TableView.setAlternatingRowColors(False)
        self.parent2TableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.parent2TableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.parent2TableView.setShowGrid(False)
        self.parent2TableView.setSortingEnabled(True)
        self.parent2TableView.setObjectName("parent2TableView")
        self.verticalLayout_3.addWidget(self.parent2TableView)
        self.verticalLayout_2.addWidget(self.parent2Container)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(StatusLayout)
        QtCore.QMetaObject.connectSlotsByName(StatusLayout)

    def retranslateUi(self, StatusLayout):
        StatusLayout.setWindowTitle(QtGui.QApplication.translate("StatusLayout", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.modifiedCheckBox.setToolTip(QtGui.QApplication.translate("StatusLayout", "Show or Hide Modified Files", None, QtGui.QApplication.UnicodeUTF8))
        self.modifiedCheckBox.setText(QtGui.QApplication.translate("StatusLayout", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.addedCheckBox.setToolTip(QtGui.QApplication.translate("StatusLayout", "Show or Hide Added Files", None, QtGui.QApplication.UnicodeUTF8))
        self.addedCheckBox.setText(QtGui.QApplication.translate("StatusLayout", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.removedCheckBox.setToolTip(QtGui.QApplication.translate("StatusLayout", "Show or Hide Removed Files", None, QtGui.QApplication.UnicodeUTF8))
        self.removedCheckBox.setText(QtGui.QApplication.translate("StatusLayout", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.deletedCheckBox.setToolTip(QtGui.QApplication.translate("StatusLayout", "Show or Hide Deleted Files", None, QtGui.QApplication.UnicodeUTF8))
        self.deletedCheckBox.setText(QtGui.QApplication.translate("StatusLayout", "!", None, QtGui.QApplication.UnicodeUTF8))
        self.unknownCheckBox.setToolTip(QtGui.QApplication.translate("StatusLayout", "Show or Hide Files not tracked by the repository", None, QtGui.QApplication.UnicodeUTF8))
        self.unknownCheckBox.setText(QtGui.QApplication.translate("StatusLayout", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.ignoredCheckBox.setToolTip(QtGui.QApplication.translate("StatusLayout", "Show or Hide Ignored Files", None, QtGui.QApplication.UnicodeUTF8))
        self.ignoredCheckBox.setText(QtGui.QApplication.translate("StatusLayout", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanCheckBox.setToolTip(QtGui.QApplication.translate("StatusLayout", "Show or Hide Files with no changes.", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanCheckBox.setText(QtGui.QApplication.translate("StatusLayout", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("StatusLayout", "Changes From Revision:", None, QtGui.QApplication.UnicodeUTF8))
        self.parent1Label.setText(QtGui.QApplication.translate("StatusLayout", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("StatusLayout", "Changes From Revision:", None, QtGui.QApplication.UnicodeUTF8))
        self.parent2Label.setText(QtGui.QApplication.translate("StatusLayout", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))

